USING AxUnit.Assert;
USING Simatic.Ax.Commands;
USING Simatic.Ax.SimpleControlModules;

NAMESPACE Simatic.Ax.axftcmlib.Motion

    {TestFixture}
    CLASS dummy
        VAR
    
        END_VAR
        
        {TestSetup}
        METHOD PUBLIC TestSetup
            ;
        END_METHOD

        {Test}
        METHOD PUBLIC TestMethod
            ;        
        END_METHOD
    END_CLASS
END_NAMESPACE
