# this workflow is useful to the apax install via setup-apax-runner@teststage. 
# This can be used, to pre test the action before it bill be released
name: test-apax-install
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout actions repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Setup the apax runner"
        uses: simatic-ax/actions/setup-apax-runner@teststage
        with:
          APAX_TOKEN: ${{ secrets.APAX_TOKEN }}

      - name: "Login to simatic-ax registry"
        if: ${{ inputs.LOGIN_SIMATIC_AX }}
        run: |
          apax login --registry "https://npm.pkg.github.com" --password "${{ secrets.SIMATIC_AX_TOKEN }}"
